"""add authentication tables

Revision ID: 2732fd410d2f
Revises: 163ae88ffc55
Create Date: 2026-08-29 12:44:01.387507

Phase 1 of the approved authentication design (see PROJECT_CONTEXT.md's
authentication decision) - schema only, no route/service/repository code
uses any of this yet. Adds three brand-new tables (`users`,
`refresh_tokens`, `password_reset_tokens` - see
`core/auth/models.py` for the full design/reasoning behind each column)
and one nullable column on an existing table
(`saved_searches.user_id`, currently unused - a later cutover phase
backfills it for existing rows and a follow-up migration makes it
`NOT NULL` once that's confirmed complete; see `core/saved_searches
/models.py`).

**Two different techniques for two different situations, same as prior
migrations in this project**: the three new tables use plain
`op.create_table()` (a new table with an inline foreign key is a single,
portable `CREATE TABLE` on every backend, including SQLite - no batch
mode needed, matching `163ae88ffc55`'s reasoning). Adding a column *and*
a foreign key constraint to the *already-existing* `saved_searches` table
needs `op.batch_alter_table()` instead (SQLite can't `ALTER TABLE ... ADD
CONSTRAINT` directly - matches `280fbde82447`'s exact precedent for the
same situation on `discovered_listings`). Autogenerated, then hand-edited
to apply batch mode to the `saved_searches` half only - autogenerate does
not know to do this on its own.

**`users.email` uniqueness is enforced case-insensitively, by the
database, via a `UNIQUE` index on `lower(email)`** - not a plain
`UNIQUE(email)` column constraint (which would let `user@example.com` and
`USER@example.com` coexist) and deliberately not PostgreSQL's `CITEXT`
either (a portable expression index needs no extension and works
identically on SQLite, which has supported expression indexes since
3.9.0). `CREATE UNIQUE INDEX ix_users_email_lower ON users (lower(email))`
is valid, native syntax on both backends this project targets - see
`core/auth/models.py`'s `User` docstring for the full reasoning. This
index is the *only* uniqueness mechanism on this column - no redundant
plain `UNIQUE(email)` constraint alongside it, since anything the plain
form would catch, this strictly stronger form catches too.

Purely additive throughout - no existing table dropped, no existing
column altered/renamed, no data touched by this migration itself. Every
existing `saved_searches` row gets `NULL` for the new `user_id` column,
which is exactly correct: no user exists yet to attribute it to.

Verified via the usual upgrade/downgrade/re-upgrade cycle against a
throwaway SQLite database before finalizing.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2732fd410d2f'
down_revision: Union[str, Sequence[str], None] = '163ae88ffc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Case-insensitive uniqueness, enforced by the database - see this
    # migration's own docstring and core/auth/models.py's User docstring.
    # No plain UniqueConstraint('email') alongside this - redundant once
    # this exists, and strictly weaker (case-sensitive) besides.
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_password_reset_tokens_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_tokens_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)

    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_saved_searches_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_saved_searches_user_id',
            'users',
            ['user_id'],
            ['id'],
            ondelete='CASCADE',
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_saved_searches_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_saved_searches_user_id'))
        batch_op.drop_column('user_id')

    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
