"""add listing product fields and saved search attribution

Revision ID: 280fbde82447
Revises: c8800c505bb9
Create Date: 2026-08-22 20:58:14.466470

Part of the Listings product-experience pass: `DiscoveredListing` never
persisted most of what a connector actually returns (price/currency/
location/seller/condition/image_url), so `GET /api/v1/listings` could
only ever return `null` for all of them - see PROJECT_CONTEXT.md and
ARCHITECTURE.md "Local persistence and duplicate detection" for the full
reasoning. Also adds `source_created_at` (the marketplace's own listing-
creation time, display-only) and `discovered_by_saved_search_id` (which
saved search's scan first found this row - a nullable FK to
`saved_searches.id`, `ON DELETE SET NULL` so deleting a saved search
never deletes or orphans the listings it found, only forgets the
attribution).

Purely additive (`add_column`/`create_index`/`create_foreign_key` only,
autogenerated by diffing the model against a database already at the
previous revision) - no data changes, no existing column altered/
dropped, safe to apply to a live database with existing rows. Every
existing row gets `NULL` for all eight new columns, which is exactly
correct (unknown, not invented) rather than any default value.

**Uses `op.batch_alter_table()`, hand-added after autogenerate** - plain
`op.create_foreign_key()`/`op.add_column()` (what autogenerate produced)
fails on SQLite with `NotImplementedError: No support for ALTER of
constraints in SQLite dialect` the moment it reaches the foreign key -
SQLite has no `ALTER TABLE ... ADD CONSTRAINT` at all. Batch mode is
Alembic's portable answer: on SQLite it transparently recreates the
table (copy-and-move); on every other backend (PostgreSQL in production)
it compiles to the exact same plain `ALTER TABLE ADD COLUMN`/
`ADD CONSTRAINT` statements autogenerate would have produced directly -
verified by running the full upgrade/downgrade/re-upgrade cycle against
a real throwaway SQLite database before finalizing, the same way every
migration in this project is checked.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280fbde82447'
down_revision: Union[str, Sequence[str], None] = 'c8800c505bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('discovered_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('seller', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('discovered_by_saved_search_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_discovered_listings_discovered_by_saved_search_id'),
            ['discovered_by_saved_search_id'],
            unique=False,
        )
        batch_op.create_foreign_key(
            'fk_discovered_listings_discovered_by_saved_search_id',
            'saved_searches',
            ['discovered_by_saved_search_id'],
            ['id'],
            ondelete='SET NULL',
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('discovered_listings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discovered_listings_discovered_by_saved_search_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_discovered_listings_discovered_by_saved_search_id'))
        batch_op.drop_column('discovered_by_saved_search_id')
        batch_op.drop_column('source_created_at')
        batch_op.drop_column('image_url')
        batch_op.drop_column('condition')
        batch_op.drop_column('seller')
        batch_op.drop_column('location')
        batch_op.drop_column('currency')
        batch_op.drop_column('price')
