"""baseline schema

Revision ID: 367e525494b6
Revises:
Create Date: 2026-08-15 21:17:31.100641

The first Alembic migration - represents the *current* model schema
(post multi-marketplace: `saved_searches` has no `marketplace` column,
`saved_search_marketplaces` is the join table), autogenerated by diffing
`Base.metadata` against a fresh, empty SQLite database (never against the
developer's real local database, and never against production). Purely
additive (`create_table`/`create_index` only) - no drops, alters, or data
changes on the upgrade path. `downgrade()` is the conventional reverse of
`upgrade()` and only runs if explicitly invoked (`alembic downgrade`) -
never automatically.

This does NOT touch or migrate any existing local SQLite data - a
pre-existing local `marketplace_alert.db` already has these tables (via
`Base.metadata.create_all()`, unchanged for SQLite - see
`core/persistence/database.py`), so running this migration against it is
a practical no-op (see the "Database" section of README.md for exactly
how local SQLite and Alembic coexist). It exists so a brand-new database
(production PostgreSQL) can be brought to today's schema in one reviewed,
versioned step - see PROJECT_CONTEXT.md and ARCHITECTURE.md.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367e525494b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('external_listing_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('listing_url', sa.String(), nullable=False),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'external_listing_id', name='uq_discovered_listing_marketplace_external_id')
    )
    op.create_index(op.f('ix_discovered_listings_marketplace'), 'discovered_listings', ['marketplace'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scan_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_search_marketplaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saved_search_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['saved_search_id'], ['saved_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_search_id', 'marketplace_name', name='uq_saved_search_marketplace')
    )
    op.create_index(op.f('ix_saved_search_marketplaces_marketplace_name'), 'saved_search_marketplaces', ['marketplace_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_search_marketplaces_marketplace_name'), table_name='saved_search_marketplaces')
    op.drop_table('saved_search_marketplaces')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_discovered_listings_marketplace'), table_name='discovered_listings')
    op.drop_table('discovered_listings')
    # ### end Alembic commands ###
