"""add metadata backfill status tracking

Revision ID: 3e288e0d0a15
Revises: 280fbde82447
Create Date: 2026-08-23 19:42:46.410714

Fixes a real production bug found while running the historical listing
metadata backfill (`core/persistence/backfill.py`,
`scripts/backfill_listing_metadata.py`): the backfill candidate query
previously selected any row with *any* enrichable field still `NULL`,
with no memory of what had already been tried. A row missing only a
field its marketplace genuinely never provides (e.g. an Etsy row's
permanently-`null` `condition`/`location`) kept matching that query
forever - since candidates are always selected newest-first up to
`--limit`, a handful of these permanently-stuck recent rows could
occupy every slot in every run, starving older, genuinely-enrichable
rows from ever being reached. See PROJECT_CONTEXT.md decision #23 for
the full root-cause writeup.

Adds two nullable columns to `discovered_listings`:
- `metadata_backfill_status` - `NULL` (never attempted/pending, the
  default), or one of `enriched`/`no_data`/`not_found`/`unsupported`
  (terminal - a row in one of these states is never selected as a
  candidate again) / `failed` (retryable - stays eligible). See
  `core/persistence/models.py`'s `BACKFILL_STATUS_*` constants and
  `DiscoveredListing.metadata_backfill_status`'s docstring for exactly
  what each value means.
- `metadata_backfill_attempted_at` - when a row was last processed by a
  real (non-dry-run) backfill attempt, for observability only; not used
  to gate candidate selection.

Purely additive (`add_column` only, autogenerated by diffing the model
against a database already at the previous revision) - no data changes,
no existing column altered or dropped, safe to apply to a live database
with existing rows. **Every existing row gets `NULL` for both new
columns** - i.e. "pending" - which is exactly correct: the unfinished
historical backfill (~178 of 187 production rows still missing metadata
as of the previous pass) must be able to continue from where it left
off, not be silently marked complete by this migration. No existing
row's `metadata_backfill_status` is ever set to a terminal value by this
migration itself - only a real backfill run (`--apply`) does that, one
row at a time, based on what it actually found.

No batch mode needed here (unlike the previous migration, which added a
foreign key) - plain `ADD COLUMN` for two nullable columns with no
constraint is already portable across SQLite and PostgreSQL. Verified via
the usual upgrade/downgrade/re-upgrade cycle against a throwaway SQLite
database before finalizing. No index added - the production table is
still small (187 rows); an index on `metadata_backfill_status` was
considered and deliberately deferred, same "don't optimize without
evidence" discipline as the price-sort index decision (PROJECT_CONTEXT.md
decision #21) - revisit if the table grows enough for this to matter.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e288e0d0a15'
down_revision: Union[str, Sequence[str], None] = '280fbde82447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('discovered_listings', sa.Column('metadata_backfill_status', sa.String(), nullable=True))
    op.add_column('discovered_listings', sa.Column('metadata_backfill_attempted_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('discovered_listings', 'metadata_backfill_attempted_at')
    op.drop_column('discovered_listings', 'metadata_backfill_status')
