"""index discovered_listings first_discovered_at

Revision ID: c8800c505bb9
Revises: 367e525494b6
Create Date: 2026-08-22 18:49:31.985837

Found during a production-hardening audit: `ListingRepository.list_recent()`
(backing `GET /api/v1/listings`, used by the mobile app's Listings screen
- the web dashboard has no listings view) orders by `first_discovered_at`
on every page load, but that column had no index - a full-table sort that
only gets slower as more listings are discovered over time. Purely
additive (`create_index` only, autogenerated by diffing the model against
a database already at the baseline revision) - no data changes, no table
drops/alters, safe to apply to a live database with existing rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8800c505bb9'
down_revision: Union[str, Sequence[str], None] = '367e525494b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_discovered_listings_first_discovered_at'), 'discovered_listings', ['first_discovered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_listings_first_discovered_at'), table_name='discovered_listings')
    # ### end Alembic commands ###
